### ISSUE TITLE
VSCode reports 'Command failed'

### ISSUE THREAD

**Issue by ohnotnow** [d9705996/vscode-tighten-lint#2]
Hi,

When I run regular `tlint` everything works as expected.  But the vscode extension is logging to the output window :
```
Executing: tlint lint --json  /path/to/my/file.php in /path/to/my/
Command failed: tlint lint --json  /path/to/my/file.php
```
If I copy'n'paste the command and run it in the terminal it runs quite happily.  I've tried the usual restart of vscode, putting the full path to tlint into the settings etc to no avail.

My vscode is version 1.42.1 in case something has broken in there.  And this is on MacOS 10.15.2 .  If there's anything else I can do to debug/help let me know :-)

**Comment by d9705996** [comment]
@ohnotnow - I have managed to replicate the issue and looks like a *bug* in tlint.  

Whenever tlint is run with `--json` it returns a non-zero value regardless of whether there are errors or not.

## No Errors
```
/root/.composer/vendor/bin/tlint lint --json  /workspaces/tlint/routes/web.php
{"errors":[]}
echo $?
1
```

## Errors

```
tlint lint --json  /workspaces/tlint/routes/web.php

{"errors":[{"line":15,"message":"! Prefer `view(..., [...])` over `view(...)->with(...)`.","source":"ArrayParametersOverViewWith"}]}
echo $?
1
```

The [error handling](https://github.com/d9705996/vscode-tighten-lint/blob/master/src/providers/LintProvider.ts#L63-L67) is returning early so no diagnostics are returned.

```
tlint lint /workspaces/tlint/routes/web.php

Lints for /workspaces/tlint/routes/web.php
============
! Prefer `view(..., [...])` over `view(...)->with(...)`.
15 : `    return view('view')`

echo $?
1

tlint lint /workspaces/tlint/routes/web.php

LGTM!
echo $?
0
```

Something changed since v3.0.9 so for now if you use v3.0.8 as below things should start working again

```
composer global require tightenco/tlint:3.0.8
```

**Comment by ohnotnow** [comment]
Ah! Jeez - I should have though to check that myself!  Good catch :-)  I'll go down a version for now.  Thanks for looking into it :-)

**Comment by d9705996** [comment]
@ohnotnow - could you try updating tlint to the latest release https://github.com/tightenco/tlint/releases/tag/v3.0.12.

Should fix your issue.

**Comment by ohnotnow** [comment]
That works perfectly!  Thank you! Much appreciated! :-)
